[project]
name = "dogu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn>=0.30.0",
    "typer>=0.12.0",
    "pydantic>=2.7.0"
]
[project.scripts]
dogu = "dogu.runner:main"
